import { BusinessSettings, ServiceCategory, Service, Professional, Client, Appointment, NotificationTemplate, FinancialTransaction } from '@/types';
import { format, addDays, subDays } from 'date-fns';

const today = new Date();
const todayStr = format(today, 'yyyy-MM-dd');
const tomorrowStr = format(addDays(today, 1), 'yyyy-MM-dd');
const yesterdayStr = format(subDays(today, 1), 'yyyy-MM-dd');

export const initialBusinessSettings: BusinessSettings = {
  id: 'a0000000-0000-0000-0000-000000000001',
  name: 'IASIS Estética Avançada',
  trade_name: 'Iasis Clinic',
  phone: '(11) 98765-4321',
  whatsapp: '11987654321',
  email: 'contato@iasisagenda.com.br',
  address: 'Av. Paulista, 1000 - Bela Vista - Sala 42',
  city: 'São Paulo',
  state: 'SP',
  zip_code: '01310-100',
  instagram: '@iasis.estetica',
  pix_key: 'pix@iasisagenda.com.br',
  pix_type: 'Email',
  require_deposit_by_default: true,
  default_deposit_percentage: 30,
  default_deposit_fixed_amount: 50,
  business_hours: {
    monday: { open: '08:00', close: '19:00', active: true },
    tuesday: { open: '08:00', close: '19:00', active: true },
    wednesday: { open: '08:00', close: '19:00', active: true },
    thursday: { open: '08:00', close: '19:00', active: true },
    friday: { open: '08:00', close: '19:00', active: true },
    saturday: { open: '08:00', close: '15:00', active: true },
    sunday: { open: '00:00', close: '00:00', active: false },
  },
  inactive_client_days: 60,
};

export const initialCategories: ServiceCategory[] = [
  { id: 'c1', name: 'Extensão de Cílios', description: 'Técnicas clássica, volume russo, híbrido e manutenção', color: '#bf3f57', sort_order: 1, active: true },
  { id: 'c2', name: 'Micropigmentação', description: 'Sobrancelhas, shadow line, fios realistas e retoques', color: '#9333ea', sort_order: 2, active: true },
  { id: 'c3', name: 'Lábios & Revitalização', description: 'Neutralização labial, efeito batom e hidragloss', color: '#db2777', sort_order: 3, active: true },
  { id: 'c4', name: 'Design de Sobrancelhas', description: 'Design personalizado com pinça, linha e aplicação de henna', color: '#ca8a04', sort_order: 4, active: true },
  { id: 'c5', name: 'Tratamentos Faciais', description: 'Limpeza de pele profunda, peeling e hidratação', color: '#059669', sort_order: 5, active: true },
];

export const initialServices: Service[] = [
  { id: 's1', category_id: 'c1', name: 'Extensão Volume Brasileiro', description: 'Aplicação de fios em formato Y proporcionando volume delicado e marcante.', duration_minutes: 120, buffer_minutes: 10, price: 180.00, requires_anamnesis: true, active: true },
  { id: 's2', category_id: 'c1', name: 'Manutenção de Cílios (até 20 dias)', description: 'Reposição dos fios com higienização prévia.', duration_minutes: 90, buffer_minutes: 10, price: 110.00, requires_anamnesis: true, active: true },
  { id: 's3', category_id: 'c2', name: 'Microblading Fio a Fio', description: 'Procedimento semipermanente para desenho natural dos fios da sobrancelha.', duration_minutes: 150, buffer_minutes: 15, price: 450.00, promotional_price: 390.00, requires_anamnesis: true, active: true },
  { id: 's4', category_id: 'c3', name: 'Hydra Gloss Lips', description: 'Hidratação profunda e regeneração labial com ácido hialurônico.', duration_minutes: 60, buffer_minutes: 10, price: 150.00, requires_anamnesis: true, active: true },
  { id: 's5', category_id: 'c4', name: 'Design de Sobrancelha com Henna', description: 'Alinhamento com visagismo facial e coloração com henna de alta fixação.', duration_minutes: 45, buffer_minutes: 10, price: 65.00, requires_anamnesis: false, active: true },
  { id: 's6', category_id: 'c5', name: 'Limpeza de Pele Profunda', description: 'Higienização, vapor de ozônio, extração manual, alta frequência e máscara calmante.', duration_minutes: 90, buffer_minutes: 15, price: 160.00, requires_anamnesis: true, active: true },
];

export const initialProfessionals: Professional[] = [
  { id: 'p1', name: 'Dra. Camila Ribeiro', nickname: 'Camila', email: 'camila@iasisagenda.com.br', phone: '(11) 99111-2233', color: '#bf3f57', specialties: ['Micropigmentação', 'Design de Sobrancelhas', 'Lábios'], commission_type: 'percentage', default_commission_rate: 45, active: true },
  { id: 'p2', name: 'Juliana Santos', nickname: 'Ju Cílios', email: 'juliana@iasisagenda.com.br', phone: '(11) 99222-3344', color: '#7c3aed', specialties: ['Extensão de Cílios', 'Lash Lifting'], commission_type: 'percentage', default_commission_rate: 40, active: true },
  { id: 'p3', name: 'Beatriz Lima', nickname: 'Bia Estética', email: 'beatriz@iasisagenda.com.br', phone: '(11) 99333-4455', color: '#0284c7', specialties: ['Limpeza de Pele', 'Tratamentos Faciais'], commission_type: 'percentage', default_commission_rate: 35, active: true },
];

export const initialClients: Client[] = [
  { id: 'u1', name: 'Mariana Alcantara', nickname: 'Mari', phone: '(11) 98877-6655', whatsapp: '11988776655', email: 'mariana.alcantara@gmail.com', birth_date: '1994-05-14', how_did_you_find_us: 'Instagram', allow_contact: true, tags: ['VIP', 'Extensão de cílios'], notes: 'Prefere cílios com efeito fox eyes e não gosta de cola com odor forte.', total_appointments: 6, total_spent: 1080.00, active: true, created_at: '2026-01-10T10:00:00Z', last_appointment_date: todayStr },
  { id: 'u2', name: 'Fernanda Souza Costa', nickname: 'Nanda', phone: '(11) 97766-5544', whatsapp: '11977665544', email: 'nandacosta@hotmail.com', birth_date: '1988-11-23', how_did_you_find_us: 'Indicação de amiga', allow_contact: true, tags: ['Frequente', 'Micropigmentação'], notes: 'Pele sensível na região das sobrancelhas.', total_appointments: 4, total_spent: 1250.00, active: true, created_at: '2026-02-15T11:30:00Z', last_appointment_date: yesterdayStr },
  { id: 'u3', name: 'Carolina Oliveira Martins', nickname: 'Carol', phone: '(11) 96655-4433', whatsapp: '11966554433', email: 'carol.martins@outlook.com', birth_date: '2001-09-08', how_did_you_find_us: 'Google', allow_contact: true, tags: ['Nova cliente'], notes: 'Primeira experiência com extensões de cílios.', total_appointments: 1, total_spent: 180.00, active: true, created_at: '2026-08-20T14:00:00Z', last_appointment_date: todayStr },
  { id: 'u4', name: 'Patricia Guimarães', nickname: 'Paty', phone: '(11) 95544-3322', whatsapp: '11955443322', email: 'paty.guimaraes@yahoo.com.br', birth_date: '1982-03-30', how_did_you_find_us: 'Instagram', allow_contact: true, tags: ['VIP', 'Lábios'], notes: 'Ama Hydra Gloss e faz manutenção mensal pontualmente.', total_appointments: 8, total_spent: 1420.00, active: true, created_at: '2025-11-05T09:00:00Z', last_appointment_date: tomorrowStr },
  { id: 'u5', name: 'Juliana Moreira Neves', nickname: 'Ju', phone: '(11) 94433-2211', whatsapp: '11944332211', email: 'ju.neves@uol.com.br', birth_date: '1990-12-19', how_did_you_find_us: 'Passou em frente', allow_contact: true, tags: ['Inativa'], notes: 'Cliente sem retorno há mais de 70 dias.', total_appointments: 2, total_spent: 220.00, active: true, created_at: '2025-09-12T16:00:00Z', last_appointment_date: '2026-05-10' },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'a1',
    client_id: 'u1',
    professional_id: 'p2',
    service_id: 's1',
    start_time: `${todayStr}T09:00:00`,
    end_time: `${todayStr}T11:00:00`,
    duration_minutes: 120,
    status: 'in_service',
    price: 180.00,
    discount: 0,
    final_price: 180.00,
    deposit_requested: true,
    deposit_amount: 54.00,
    deposit_paid: true,
    deposit_paid_at: `${todayStr}T08:30:00`,
    payment_method: 'pix',
    payment_status: 'paid',
    notes: 'Volume brasileiro efeito fox.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a2',
    client_id: 'u3',
    professional_id: 'p1',
    service_id: 's5',
    start_time: `${todayStr}T11:30:00`,
    end_time: `${todayStr}T12:15:00`,
    duration_minutes: 45,
    status: 'confirmed',
    price: 65.00,
    discount: 0,
    final_price: 65.00,
    deposit_requested: false,
    deposit_amount: 0,
    deposit_paid: false,
    payment_method: 'credit_card',
    payment_status: 'pending',
    notes: 'Primeira vez no design com Henna.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a3',
    client_id: 'u4',
    professional_id: 'p1',
    service_id: 's4',
    start_time: `${todayStr}T14:00:00`,
    end_time: `${todayStr}T15:00:00`,
    duration_minutes: 60,
    status: 'scheduled',
    price: 150.00,
    discount: 15.00,
    final_price: 135.00,
    deposit_requested: true,
    deposit_amount: 45.00,
    deposit_paid: true,
    payment_method: 'pix',
    payment_status: 'pending',
    notes: 'Hydra gloss lips manutenção mensal.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a4',
    client_id: 'u2',
    professional_id: 'p3',
    service_id: 's6',
    start_time: `${todayStr}T16:00:00`,
    end_time: `${todayStr}T17:30:00`,
    duration_minutes: 90,
    status: 'scheduled',
    price: 160.00,
    discount: 0,
    final_price: 160.00,
    deposit_requested: false,
    deposit_amount: 0,
    deposit_paid: false,
    payment_status: 'pending',
    notes: 'Limpeza de pele profunda com extração.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a5',
    client_id: 'u1',
    professional_id: 'p2',
    service_id: 's2',
    start_time: `${tomorrowStr}T10:00:00`,
    end_time: `${tomorrowStr}T11:30:00`,
    duration_minutes: 90,
    status: 'confirmed',
    price: 110.00,
    discount: 0,
    final_price: 110.00,
    deposit_requested: false,
    deposit_amount: 0,
    deposit_paid: false,
    payment_status: 'pending',
    notes: 'Manutenção de cílios.',
    created_at: `${todayStr}T08:00:00Z`,
  },
];

export const initialTemplates: NotificationTemplate[] = [
  {
    id: 'm1',
    category: 'reminder_24h',
    title: 'Lembrete de Atendimento (24h antes)',
    content: 'Olá, {{cliente}}! Tudo bem? 😊\n\nPassando para confirmar seu atendimento de amanhã, dia {{data}}, às {{hora}}, para o procedimento: *{{servico}}*.\nSeu atendimento será com {{profissional}} no endereço: Av. Paulista, 1000.\n\nPor favor, responda com *CONFIRMAR* ou nos avise caso precise reagendar!',
    is_default: true,
  },
  {
    id: 'm2',
    category: 'confirmation',
    title: 'Confirmação de Agendamento',
    content: 'Oi, {{cliente}}! Seu agendamento foi realizado com sucesso!\n\n📅 Data: {{data}}\n⏰ Horário: {{hora}}\n💅 Procedimento: {{servico}}\n👩‍⚕️ Profissional: {{profissional}}\n💰 Valor: R$ {{valor}}\n\nEstamos ansiosas para te receber no espaço IASIS! ✨',
    is_default: true,
  },
  {
    id: 'm3',
    category: 'deposit_request',
    title: 'Solicitação de Sinal de Reserva',
    content: 'Olá, {{cliente}}! Para garantir o seu horário no dia {{data}} às {{hora}}, solicitamos o envio do sinal de reserva de R$ {{valor_sinal}}.\n\nChave PIX: pix@iasisagenda.com.br\nFavorecido: IASIS Estética\n\nPor favor, nos envie o comprovante assim que realizar o pagamento. O valor será abatido no total do seu procedimento! 💕',
    is_default: true,
  },
  {
    id: 'm4',
    category: 'birthday',
    title: 'Felicitações de Aniversário',
    content: 'Parabéns, {{cliente}}! 🎂🎉\nA equipe IASIS AGENDA deseja a você um novo ciclo repleto de realizações, saúde e beleza!\n\nPreparamos um presente especial para o seu mês: *15% de desconto* em qualquer procedimento. Agende seu horário!',
    is_default: true,
  },
  {
    id: 'm5',
    category: 'inactive_client',
    title: 'Recuperação de Cliente Inativa',
    content: 'Olá, {{cliente}}, estamos com saudades de você aqui no espaço IASIS! ✨\n\nFaz um tempinho desde seu último procedimento de {{servico}}. Que tal renovar seus cuidados esta semana? Temos horários especiais disponíveis para você!',
    is_default: true,
  },
];
