import {
  BusinessSettings,
  ServiceCategory,
  Service,
  Professional,
  Client,
  Appointment,
  NotificationTemplate,
  AnamnesisTemplate,
  AnamnesisRecord,
  TreatmentEvolution,
  TreatmentPhoto,
  Product,
} from '@/types';
import { format, addDays, subDays } from 'date-fns';

const today = new Date();
const todayStr = format(today, 'yyyy-MM-dd');
const tomorrowStr = format(addDays(today, 1), 'yyyy-MM-dd');
const yesterdayStr = format(subDays(today, 1), 'yyyy-MM-dd');

export const initialBusinessSettings: BusinessSettings = {
  id: 'a0000000-0000-0000-0000-000000000001',
  name: 'IASIS Estética Avançada',
  trade_name: 'Iasis Clinic',
  phone: '(11) 98765-4321',
  whatsapp: '11987654321',
  email: 'contato@iasisagenda.com.br',
  address: 'Av. Paulista, 1000 - Bela Vista - Sala 42',
  city: 'São Paulo',
  state: 'SP',
  zip_code: '01310-100',
  instagram: '@iasis.estetica',
  pix_key: 'pix@iasisagenda.com.br',
  pix_type: 'Email',
  require_deposit_by_default: true,
  default_deposit_percentage: 30,
  default_deposit_fixed_amount: 50,
  business_hours: {
    monday: { open: '08:00', close: '19:00', active: true },
    tuesday: { open: '08:00', close: '19:00', active: true },
    wednesday: { open: '08:00', close: '19:00', active: true },
    thursday: { open: '08:00', close: '19:00', active: true },
    friday: { open: '08:00', close: '19:00', active: true },
    saturday: { open: '08:00', close: '15:00', active: true },
    sunday: { open: '00:00', close: '00:00', active: false },
  },
  inactive_client_days: 60,
};

export const initialCategories: ServiceCategory[] = [
  { id: 'c1', name: 'Extensão de Cílios', description: 'Técnicas clássica, volume russo, híbrido e manutenção', color: '#bf3f57', sort_order: 1, active: true },
  { id: 'c2', name: 'Micropigmentação', description: 'Sobrancelhas, shadow line, fios realistas e retoques', color: '#9333ea', sort_order: 2, active: true },
  { id: 'c3', name: 'Lábios & Revitalização', description: 'Neutralização labial, efeito batom e hidragloss', color: '#db2777', sort_order: 3, active: true },
  { id: 'c4', name: 'Design de Sobrancelhas', description: 'Design personalizado com pinça, linha e aplicação de henna', color: '#ca8a04', sort_order: 4, active: true },
  { id: 'c5', name: 'Tratamentos Faciais', description: 'Limpeza de pele profunda, peeling e hidratação', color: '#059669', sort_order: 5, active: true },
];

export const initialServices: Service[] = [
  { id: 's1', category_id: 'c1', name: 'Extensão Volume Brasileiro', description: 'Aplicação de fios em formato Y proporcionando volume delicado e marcante.', duration_minutes: 120, buffer_minutes: 10, price: 180.00, requires_anamnesis: true, active: true },
  { id: 's2', category_id: 'c1', name: 'Manutenção de Cílios (até 20 dias)', description: 'Reposição dos fios com higienização prévia.', duration_minutes: 90, buffer_minutes: 10, price: 110.00, requires_anamnesis: true, active: true },
  { id: 's3', category_id: 'c2', name: 'Microblading Fio a Fio', description: 'Procedimento semipermanente para desenho natural dos fios da sobrancelha.', duration_minutes: 150, buffer_minutes: 15, price: 450.00, promotional_price: 390.00, requires_anamnesis: true, active: true },
  { id: 's4', category_id: 'c3', name: 'Hydra Gloss Lips', description: 'Hidratação profunda e regeneração labial com ácido hialurônico.', duration_minutes: 60, buffer_minutes: 10, price: 150.00, requires_anamnesis: true, active: true },
  { id: 's5', category_id: 'c4', name: 'Design de Sobrancelha com Henna', description: 'Alinhamento com visagismo facial e coloração com henna de alta fixação.', duration_minutes: 45, buffer_minutes: 10, price: 65.00, requires_anamnesis: false, active: true },
  { id: 's6', category_id: 'c5', name: 'Limpeza de Pele Profunda', description: 'Higienização, vapor de ozônio, extração manual, alta frequência e máscara calmante.', duration_minutes: 90, buffer_minutes: 15, price: 160.00, requires_anamnesis: true, active: true },
];

export const initialProfessionals: Professional[] = [
  { id: 'p1', name: 'Dra. Camila Ribeiro', nickname: 'Camila', email: 'camila@iasisagenda.com.br', phone: '(11) 99111-2233', color: '#bf3f57', specialties: ['Micropigmentação', 'Design de Sobrancelhas', 'Lábios'], commission_type: 'percentage', default_commission_rate: 45, active: true },
  { id: 'p2', name: 'Juliana Santos', nickname: 'Ju Cílios', email: 'juliana@iasisagenda.com.br', phone: '(11) 99222-3344', color: '#7c3aed', specialties: ['Extensão de Cílios', 'Lash Lifting'], commission_type: 'percentage', default_commission_rate: 40, active: true },
  { id: 'p3', name: 'Beatriz Lima', nickname: 'Bia Estética', email: 'beatriz@iasisagenda.com.br', phone: '(11) 99333-4455', color: '#0284c7', specialties: ['Limpeza de Pele', 'Tratamentos Faciais'], commission_type: 'percentage', default_commission_rate: 35, active: true },
];

export const initialClients: Client[] = [
  { id: 'u1', name: 'Mariana Alcantara', nickname: 'Mari', phone: '(11) 98877-6655', whatsapp: '11988776655', email: 'mariana.alcantara@gmail.com', birth_date: '1994-05-14', how_did_you_find_us: 'Instagram', allow_contact: true, tags: ['VIP', 'Extensão de cílios'], notes: 'Prefere cílios com efeito fox eyes e não gosta de cola com odor forte.', total_appointments: 6, total_spent: 1080.00, active: true, created_at: '2026-01-10T10:00:00Z', last_appointment_date: todayStr },
  { id: 'u2', name: 'Fernanda Souza Costa', nickname: 'Nanda', phone: '(11) 97766-5544', whatsapp: '11977665544', email: 'nandacosta@hotmail.com', birth_date: '1988-11-23', how_did_you_find_us: 'Indicação de amiga', allow_contact: true, tags: ['Frequente', 'Micropigmentação'], notes: 'Pele sensível na região das sobrancelhas.', total_appointments: 4, total_spent: 1250.00, active: true, created_at: '2026-02-15T11:30:00Z', last_appointment_date: yesterdayStr },
  { id: 'u3', name: 'Carolina Oliveira Martins', nickname: 'Carol', phone: '(11) 96655-4433', whatsapp: '11966554433', email: 'carol.martins@outlook.com', birth_date: '2001-09-08', how_did_you_find_us: 'Google', allow_contact: true, tags: ['Nova cliente'], notes: 'Primeira experiência com extensões de cílios.', total_appointments: 1, total_spent: 180.00, active: true, created_at: '2026-08-20T14:00:00Z', last_appointment_date: todayStr },
  { id: 'u4', name: 'Patricia Guimarães', nickname: 'Paty', phone: '(11) 95544-3322', whatsapp: '11955443322', email: 'paty.guimaraes@yahoo.com.br', birth_date: '1982-03-30', how_did_you_find_us: 'Instagram', allow_contact: true, tags: ['VIP', 'Lábios'], notes: 'Ama Hydra Gloss e faz manutenção mensal pontualmente.', total_appointments: 8, total_spent: 1420.00, active: true, created_at: '2025-11-05T09:00:00Z', last_appointment_date: tomorrowStr },
  { id: 'u5', name: 'Juliana Moreira Neves', nickname: 'Ju', phone: '(11) 94433-2211', whatsapp: '11944332211', email: 'ju.neves@uol.com.br', birth_date: '1990-12-19', how_did_you_find_us: 'Passou em frente', allow_contact: true, tags: ['Inativa'], notes: 'Cliente sem retorno há mais de 70 dias.', total_appointments: 2, total_spent: 220.00, active: true, created_at: '2025-09-12T16:00:00Z', last_appointment_date: '2026-05-10' },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'a1',
    client_id: 'u1',
    professional_id: 'p2',
    service_id: 's1',
    start_time: `${todayStr}T09:00:00`,
    end_time: `${todayStr}T11:00:00`,
    duration_minutes: 120,
    status: 'in_service',
    price: 180.00,
    discount: 0,
    final_price: 180.00,
    deposit_requested: true,
    deposit_amount: 54.00,
    deposit_paid: true,
    deposit_paid_at: `${todayStr}T08:30:00`,
    payment_method: 'pix',
    payment_status: 'paid',
    notes: 'Volume brasileiro efeito fox.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a2',
    client_id: 'u3',
    professional_id: 'p1',
    service_id: 's5',
    start_time: `${todayStr}T11:30:00`,
    end_time: `${todayStr}T12:15:00`,
    duration_minutes: 45,
    status: 'confirmed',
    price: 65.00,
    discount: 0,
    final_price: 65.00,
    deposit_requested: false,
    deposit_amount: 0,
    deposit_paid: false,
    payment_method: 'credit_card',
    payment_status: 'pending',
    notes: 'Primeira vez no design com Henna.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a3',
    client_id: 'u4',
    professional_id: 'p1',
    service_id: 's4',
    start_time: `${todayStr}T14:00:00`,
    end_time: `${todayStr}T15:00:00`,
    duration_minutes: 60,
    status: 'scheduled',
    price: 150.00,
    discount: 15.00,
    final_price: 135.00,
    deposit_requested: true,
    deposit_amount: 45.00,
    deposit_paid: true,
    payment_method: 'pix',
    payment_status: 'pending',
    notes: 'Hydra gloss lips manutenção mensal.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a4',
    client_id: 'u2',
    professional_id: 'p3',
    service_id: 's6',
    start_time: `${todayStr}T16:00:00`,
    end_time: `${todayStr}T17:30:00`,
    duration_minutes: 90,
    status: 'scheduled',
    price: 160.00,
    discount: 0,
    final_price: 160.00,
    deposit_requested: false,
    deposit_amount: 0,
    deposit_paid: false,
    payment_status: 'pending',
    notes: 'Limpeza de pele profunda com extração.',
    created_at: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'a5',
    client_id: 'u1',
    professional_id: 'p2',
    service_id: 's2',
    start_time: `${tomorrowStr}T10:00:00`,
    end_time: `${tomorrowStr}T11:30:00`,
    duration_minutes: 90,
    status: 'confirmed',
    price: 110.00,
    discount: 0,
    final_price: 110.00,
    deposit_requested: false,
    deposit_amount: 0,
    deposit_paid: false,
    payment_status: 'pending',
    notes: 'Manutenção de cílios.',
    created_at: `${todayStr}T08:00:00Z`,
  },
];

export const initialTemplates: NotificationTemplate[] = [
  {
    id: 'm1',
    category: 'reminder_24h',
    title: 'Lembrete de Atendimento (24h antes)',
    content: 'Olá, {{cliente}}! Tudo bem? 😊\n\nPassando para confirmar seu atendimento de amanhã, dia {{data}}, às {{hora}}, para o procedimento: *{{servico}}*.\nSeu atendimento será com {{profissional}} no endereço: Av. Paulista, 1000.\n\nPor favor, responda com *CONFIRMAR* ou nos avise caso precise reagendar!',
    is_default: true,
  },
  {
    id: 'm2',
    category: 'confirmation',
    title: 'Confirmação de Agendamento',
    content: 'Oi, {{cliente}}! Seu agendamento foi realizado com sucesso!\n\n📅 Data: {{data}}\n⏰ Horário: {{hora}}\n💅 Procedimento: {{servico}}\n👩‍⚕️ Profissional: {{profissional}}\n💰 Valor: R$ {{valor}}\n\nEstamos ansiosas para te receber no espaço IASIS! ✨',
    is_default: true,
  },
  {
    id: 'm3',
    category: 'deposit_request',
    title: 'Solicitação de Sinal de Reserva',
    content: 'Olá, {{cliente}}! Para garantir o seu horário no dia {{data}} às {{hora}}, solicitamos o envio do sinal de reserva de R$ {{valor_sinal}}.\n\nChave PIX: pix@iasisagenda.com.br\nFavorecido: IASIS Estética\n\nPor favor, nos envie o comprovante assim que realizar o pagamento. O valor será abatido no total do seu procedimento! 💕',
    is_default: true,
  },
  {
    id: 'm4',
    category: 'birthday',
    title: 'Felicitações de Aniversário',
    content: 'Parabéns, {{cliente}}! 🎂🎉\nA equipe IASIS AGENDA deseja a você um novo ciclo repleto de realizações, saúde e beleza!\n\nPreparamos um presente especial para o seu mês: *15% de desconto* em qualquer procedimento. Agende seu horário!',
    is_default: true,
  },
  {
    id: 'm5',
    category: 'inactive_client',
    title: 'Recuperação de Cliente Inativa',
    content: 'Olá, {{cliente}}, estamos com saudades de você aqui no espaço IASIS! ✨\n\nFaz um tempinho desde seu último procedimento de {{servico}}. Que tal renovar seus cuidados esta semana? Temos horários especiais disponíveis para você!',
    is_default: true,
  },
];

// =========================================================
// 4 MODELOS DE ANAMNESE PRÉ-CONFIGURADOS
// =========================================================
export const initialAnamnesisTemplates: AnamnesisTemplate[] = [
  {
    id: 't-cilios',
    title: 'Ficha de Extensão de Cílios',
    description: 'Avaliação oftalmológica e estética para aplicação e manutenção de fios.',
    category: 'cilios',
    requires_signature: true,
    active: true,
    terms_text: 'Declaro que as informações acima são verdadeiras e estou ciente dos cuidados pós-procedimento (não molhar nas primeiras 24h, não usar máscara à base de óleo, higienizar diariamente).',
    created_at: '2026-01-01T00:00:00Z',
    fields: [
      { id: 'f_c1', type: 'single_choice', label: 'Usa lentes de contato?', required: true, options: ['Não', 'Sim (removidas para o atendimento)', 'Sim (com lentes)'] },
      { id: 'f_c2', type: 'single_choice', label: 'Já teve reação alérgica a adesivo/cola ou cianoacrilato?', required: true, options: ['Não', 'Sim', 'Não sei informar'] },
      { id: 'f_c3', type: 'checkbox', label: 'Possui sensibilidade ou lacrimejamento excessivo nos olhos?', required: false },
      { id: 'f_c4', type: 'single_choice', label: 'Costuma dormir de bruços ou de lado?', required: false, options: ['De costas', 'De lado', 'De bruços'] },
      { id: 'f_c5', type: 'single_choice', label: 'Efeito / Mapping Desejado', required: true, options: ['Volume Brasileiro (Y)', 'Volume Russo', 'Clássico Fio a Fio', 'Efeito Fox Eyes', 'Efeito Boneca'] },
      { id: 'f_c6', type: 'short_text', label: 'Curvatura e Espessura Utilizada', placeholder: 'Ex: Curvatura D, Espessura 0.07, Tamanhos 8 ao 13mm', required: false },
      { id: 'f_c7', type: 'long_text', label: 'Observações de Saúde Ocular', placeholder: 'Histórico de conjuntivite, blefarite, cirurgia ocular recente...', required: false },
    ],
  },
  {
    id: 't-labios',
    title: 'Ficha de Micropigmentação de Lábios',
    description: 'Análise labial, histórico de herpes, tom natural e técnica de revitalização/efeito batom.',
    category: 'labios',
    requires_signature: true,
    active: true,
    terms_text: 'Autorizo a realização da micropigmentação labial e compreendo o processo de cicatrização (clareamento de até 50% nos primeiros 30 dias e necessidade de retoque se aplicável).',
    created_at: '2026-01-01T00:00:00Z',
    fields: [
      { id: 'f_l1', type: 'single_choice', label: 'Histórico de Herpes Labial?', required: true, options: ['Nunca tive', 'Já tive episódios no passado', 'Frequentemente'] },
      { id: 'f_l2', type: 'single_choice', label: 'Já realizou preenchimento com ácido hialurônico nos lábios?', required: true, options: ['Não', 'Sim (há menos de 3 meses)', 'Sim (há mais de 3 meses)'] },
      { id: 'f_l3', type: 'single_choice', label: 'Tom natural dos lábios', required: true, options: ['Pálido/Claro', 'Rosado', 'Arroxeado/Escuro (Necessita Neutralização)', 'Manchado'] },
      { id: 'f_l4', type: 'single_choice', label: 'Técnica Escolhida', required: true, options: ['Hydra Gloss Lips', 'Revitalização Labial / Aquarela', 'Efeito Batom (Full Lips)', 'Neutralização Labial'] },
      { id: 'f_l5', type: 'short_text', label: 'Pigmento / Mistura de Cores Escolhida', placeholder: 'Ex: RB Kollors Red Rose + Pitanga', required: false },
      { id: 'f_l6', type: 'checkbox', label: 'Está ciente da recomendação de profilaxia antiviral caso tenha histórico de herpes?', required: true },
      { id: 'f_l7', type: 'long_text', label: 'Alergias a Anestésicos Tópicos ou Cosméticos', placeholder: 'Ex: Lidocaína, Epinefrina, etc.', required: false },
    ],
  },
  {
    id: 't-sobrancelhas',
    title: 'Ficha de Micropigmentação de Sobrancelhas',
    description: 'Análise de visagismo, tipo de pele, uso de ácidos e técnica Microblading/Shadow.',
    category: 'sobrancelhas',
    requires_signature: true,
    active: true,
    terms_text: 'Aprovo o desenho e a cor definidos em conjunto com a profissional e declaro que não omiti nenhuma condição de saúde.',
    created_at: '2026-01-01T00:00:00Z',
    fields: [
      { id: 'f_s1', type: 'single_choice', label: 'Tipo de Pele na região das sobrancelhas', required: true, options: ['Normal', 'Seca', 'Mista', 'Muito Oleosa'] },
      { id: 'f_s2', type: 'single_choice', label: 'Tendência a Queloides ou Cicatrização Hipertrófica?', required: true, options: ['Não', 'Sim', 'Não sei'] },
      { id: 'f_s3', type: 'checkbox', label: 'Está em uso de ácidos faciais, peeling químico ou Roacutan?', required: true },
      { id: 'f_s4', type: 'single_choice', label: 'Técnica de Sobrancelhas', required: true, options: ['Microblading Fio a Fio', 'Shadow Line / Ombré', 'Híbrida (Fios + Shadow)', 'Nanoblading'] },
      { id: 'f_s5', type: 'short_text', label: 'Pigmento e Lâmina Utilizada', placeholder: 'Ex: Lâmina 18U Flex, Pigmento Castanho Médio', required: false },
      { id: 'f_s6', type: 'single_choice', label: 'Procedimento Anterior na região?', required: true, options: ['Nunca fez', 'Fez micropigmentação antiga (desbotada)', 'Possui pigmento residual avermelhado/acinzentado'] },
      { id: 'f_s7', type: 'long_text', label: 'Medicamentos de uso contínuo (Anticoagulantes, etc.)', placeholder: 'Ex: AAS, anticoagulantes, anti-inflamatórios...', required: false },
    ],
  },
  {
    id: 't-remocao',
    title: 'Ficha de Remoção de Tatuagem / Micropigmentação',
    description: 'Protocolo de despigmentação a laser / químico, fototipo cutâneo e histórico.',
    category: 'remocao',
    requires_signature: true,
    active: true,
    terms_text: 'Compreendo que a remoção é um tratamento progressivo que requer múltiplas sessões com intervalo mínimo de 30 a 45 dias para cicatrização completa.',
    created_at: '2026-01-01T00:00:00Z',
    fields: [
      { id: 'f_r1', type: 'single_choice', label: 'Fototipo de Pele (Escala Fitzpatrick)', required: true, options: ['Fototipo I (Muito Clara)', 'Fototipo II (Clara)', 'Fototipo III (Morena Clara)', 'Fototipo IV (Morena Moderada)', 'Fototipo V (Morena Escura)', 'Fototipo VI (Negra)'] },
      { id: 'f_r2', type: 'single_choice', label: 'Tipo de Remoção', required: true, options: ['Remoção de Tatuagem Corporal', 'Despigmentação de Sobrancelhas Antigas', 'Remoção de Micropigmentação Labial'] },
      { id: 'f_r3', type: 'short_text', label: 'Tempo aproximado do desenho na pele', placeholder: 'Ex: Feito há 3 anos', required: true },
      { id: 'f_r4', type: 'single_choice', label: 'Cores predominantes do pigmento', required: true, options: ['Preto / Azul Escuro Puro', 'Colorido (Vermelho/Amarelo)', 'Mistura de Pigmentos com Dióxido de Titânio'] },
      { id: 'f_r5', type: 'scale', label: 'Sensibilidade à Dor (1 a 5)', min: 1, max: 5, required: false },
      { id: 'f_r6', type: 'checkbox', label: 'Está ciente da proibição de exposição solar durante todo o ciclo do tratamento?', required: true },
      { id: 'f_r7', type: 'long_text', label: 'Reações ou sensibilidades dermatológicas prévias', placeholder: 'Dermatite, psoríase, alergia a pomadas...', required: false },
    ],
  },
];

// Fichas preenchidas de exemplo
export const initialAnamnesisRecords: AnamnesisRecord[] = [
  {
    id: 'rec-1',
    client_id: 'u1',
    template_id: 't-cilios',
    template_title: 'Ficha de Extensão de Cílios',
    fields_snapshot: initialAnamnesisTemplates[0].fields,
    answers: {
      f_c1: 'Não',
      f_c2: 'Não',
      f_c3: false,
      f_c4: 'De lado',
      f_c5: 'Volume Brasileiro (Y)',
      f_c6: 'Curvatura D, 0.07, 8 ao 12mm',
      f_c7: 'Sem queixas oculares.',
    },
    signed_at: '2026-08-15T10:30:00Z',
    notes: 'Cliente tolerou muito bem a aplicação.',
    created_at: '2026-08-15T10:30:00Z',
  },
  {
    id: 'rec-2',
    client_id: 'u4',
    template_id: 't-labios',
    template_title: 'Ficha de Micropigmentação de Lábios',
    fields_snapshot: initialAnamnesisTemplates[1].fields,
    answers: {
      f_l1: 'Nunca tive',
      f_l2: 'Não',
      f_l3: 'Pálido/Claro',
      f_l4: 'Hydra Gloss Lips',
      f_l5: 'Sérum Ácido Hialurônico + Pigmento Coral Peach',
      f_l6: true,
      f_l7: 'Nenhuma alergia.',
    },
    signed_at: '2026-07-20T14:00:00Z',
    notes: 'Realizado Hydra Gloss para hidratação intensiva.',
    created_at: '2026-07-20T14:00:00Z',
  }
];

// Produtos em Estoque
export const initialProducts: Product[] = [
  { id: 'prd-1', name: 'Adesivo / Cola Master Elite', category: 'Cílios', brand: 'Master', cost_price: 120.00, stock_quantity: 4, min_stock_alert: 2, unit: 'un', expiration_date: '2027-02-28', batch_number: 'ME-8842', active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'prd-2', name: 'Fios Volume Brasileiro Nagaraku Y (Mix)', category: 'Cílios', brand: 'Nagaraku', cost_price: 38.00, stock_quantity: 12, min_stock_alert: 4, unit: 'un', active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'prd-3', name: 'Pigmento Red Rose RB Kollors', category: 'Micropigmentação', brand: 'RB Kollors', cost_price: 155.00, stock_quantity: 3, min_stock_alert: 1, unit: 'un', expiration_date: '2027-08-15', batch_number: 'RB-9912', active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'prd-4', name: 'Pigmento Total Black RB Kollors', category: 'Micropigmentação', brand: 'RB Kollors', cost_price: 155.00, stock_quantity: 2, min_stock_alert: 1, unit: 'un', expiration_date: '2027-09-30', batch_number: 'RB-9944', active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'prd-5', name: 'Ácido Hialurônico Hydra Gloss 15ml', category: 'Lábios', brand: 'Dermachem', cost_price: 45.00, stock_quantity: 8, min_stock_alert: 2, unit: 'un', expiration_date: '2027-11-20', active: true, created_at: '2026-01-10T10:00:00Z' },
  { id: 'prd-6', name: 'Henna para Sobrancelhas Castanho Médio', category: 'Sobrancelhas', brand: 'Della & Delle', cost_price: 28.00, stock_quantity: 6, min_stock_alert: 2, unit: 'un', active: true, created_at: '2026-01-10T10:00:00Z' },
];

// Evolução de Procedimentos
export const initialEvolutions: TreatmentEvolution[] = [
  {
    id: 'evo-1',
    client_id: 'u1',
    professional_id: 'p2',
    procedure_name: 'Extensão Volume Brasileiro',
    session_number: 1,
    date: yesterdayStr,
    description: 'Aplicação completa dos fios Y, mapping fox eyes nos tamanhos 8 a 12mm. Isolamento perfeito dos fios naturais.',
    products_used: ['Adesivo / Cola Master Elite', 'Fios Volume Brasileiro Nagaraku Y (Mix)'],
    reaction_result: 'Excelente acoplagem, sem vermelhidão ou ardência.',
    recommendations: 'Evitar vapor e água nas primeiras 24h. Escovar diariamente com a escovinha fornecida.',
    next_session_date: format(addDays(today, 20), 'yyyy-MM-dd'),
    created_at: `${yesterdayStr}T11:00:00Z`,
  },
  {
    id: 'evo-2',
    client_id: 'u4',
    professional_id: 'p1',
    procedure_name: 'Hydra Gloss Lips',
    session_number: 2,
    date: subDays(today, 10).toISOString().split('T')[0],
    description: 'Esfoliação suave labial, infusão de ácido hialurônico através de microagulhamento estético e pigmento translúcido.',
    products_used: ['Ácido Hialurônico Hydra Gloss 15ml', 'Pigmento Red Rose RB Kollors'],
    reaction_result: 'Lábios extremamente hidratados com discreto brilho rosado.',
    recommendations: 'Aplicar lip balm cicatrizante com filtro solar diariamente.',
    next_session_date: format(addDays(today, 20), 'yyyy-MM-dd'),
    created_at: `${subDays(today, 10).toISOString().split('T')[0]}T15:00:00Z`,
  }
];

// Fotos Antes e Depois
export const initialPhotos: TreatmentPhoto[] = [
  {
    id: 'pho-1',
    client_id: 'u1',
    procedure_name: 'Extensão Volume Brasileiro',
    photo_type: 'before',
    image_url: 'https://images.unsplash.com/photo-1583001809873-a1284a51e600?auto=format&fit=crop&w=600&q=80',
    date: yesterdayStr,
    notes: 'Cílios naturais curtos e retos.',
    created_at: `${yesterdayStr}T09:10:00Z`,
  },
  {
    id: 'pho-2',
    client_id: 'u1',
    procedure_name: 'Extensão Volume Brasileiro',
    photo_type: 'after',
    image_url: 'https://images.unsplash.com/photo-1588515724527-074a7a56616c?auto=format&fit=crop&w=600&q=80',
    date: yesterdayStr,
    notes: 'Volume brasileiro finalizado com curvatura D.',
    created_at: `${yesterdayStr}T11:15:00Z`,
  },
  {
    id: 'pho-3',
    client_id: 'u4',
    procedure_name: 'Hydra Gloss Lips',
    photo_type: 'before',
    image_url: 'https://images.unsplash.com/photo-1588515724527-074a7a56616c?auto=format&fit=crop&w=600&q=80',
    date: subDays(today, 10).toISOString().split('T')[0],
    notes: 'Lábios ressecados.',
    created_at: `${subDays(today, 10).toISOString().split('T')[0]}T14:00:00Z`,
  },
  {
    id: 'pho-4',
    client_id: 'u4',
    procedure_name: 'Hydra Gloss Lips',
    photo_type: 'after',
    image_url: 'https://images.unsplash.com/photo-1583001809873-a1284a51e600?auto=format&fit=crop&w=600&q=80',
    date: subDays(today, 10).toISOString().split('T')[0],
    notes: 'Lábios volumosos e revitalizados.',
    created_at: `${subDays(today, 10).toISOString().split('T')[0]}T15:00:00Z`,
  }
];
